<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.8.1" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.5" />
    <PackageReference Include="xunit.v3" Version="3.2.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/SmartCities.Api/SmartCities.Api.csproj" />
    <ProjectReference Include="../../src/SmartCities.Application/SmartCities.Application.csproj" />
    <ProjectReference Include="../../src/SmartCities.Core/SmartCities.Core.csproj" />
  </ItemGroup>
</Project>
